### PR TITLE
ScrollBar refactoring

### PR DESCRIPTION
**Pull request by MShark67**

### CODE REVIEW

**Comment by pyscripter** [comment]
Looks good to me.  Could/should TSynScrollBarHandler be moved to SynEditMiscClasses.pas?

**Comment by pyscripter** [comment]
Without thinking it through, it seams to me that eoScrollPastEol should not affect the horizontal scrollbar.

**Comment by MShark67** [comment]
It can be moved for sure.  My proposed change for eoScrollPastEOL only affects things if you "right arrow" such that Left > 1.  It can easily be removed if it causes issues.  I also didn't want to show the horizontal scrollbar all the time, so I didn't do is that way.

**Comment by pyscripter** [comment]
Can we put this on hold?  In the DWrite branch I will be replacing GetLengthOfLongestLine with GetMaxLineWidth (returning pixels) so it may make sense to set the horizontal scrolling in pixels.
If the DWrite branch works well we would not like to do the integration with this PR twice.

**Comment by MShark67** [comment]
Of course, no worries at all.  The units (pixels or chars or whatever) of the scrollbars are arbitrary.  It's just that the current "fixed width chars" nature of the Editor makes char units a bit easier to deal with (otherwise it'll just have to translate nPos or nTrackPos to "logical" coords which is easy enough.)  I assume when you say "replace" above that we'd still have both GetMaxLineCharWidth and GetMaxLinePixelWidth (whatever they get called.)  Btw is the idea to support non-fixed-width fonts?  I'd love to see that though I can imagine it might make certain features difficult (such as column selections.)

**Comment by pyscripter** [comment]
Chinese chars are wider and you also have surrogate pairs etc. (many codepoints mapping into one grapheme),  so in unicode codepoints do not necessarily relate to width. See #26 for details. So you have to measure actual width of lines. GetLengthOfLongestLine is not useful, there is no need to keep it.

Currently SynEdit only deals with "Wide glyphs" but the way it does it is cumbersome and limited.  ExpandAtWideGlyphs and the like will  go away.

**Comment by MShark67** [comment]
Very cool!  For some reason I was thinking I used "GetLengthOfLongestLine" in my own code... I'm not, so I'm all for removing stuff that's not needed.

**Pull request closed without merging**
