### PR TITLE
SQL Highlighter refactoring

### PR DESCRIPTION
**Pull request by MShark67**
Working towards removing TSynHashEntryList from all the highlighters.  Ten more to go.

### CODE REVIEW

**Comment by pyscripter** [comment]
Great! Keep on committing.
I will merge when you are done.

**Comment by pyscripter** [comment]
Well done!

Why don't you remove the HashEntries file in the same PR?

**Comment by MShark67** [comment]
Will do!   Hold off on this for now, I'll let you know when I've cleaned up a few things.

**Comment by MShark67** [comment]
I believe this is ready to go whenever you feel is good.  I commented on the new wordwrap commit, it's 3.5 to 4 times faster in all my tests.   Nicely done!

**Comment by pyscripter** [comment]
Thanks very much!  Please have a look at the proposals in discussions.

**Pull request merged**
