### PR TITLE
DWScript name and unit scope update.

### PR DESCRIPTION
**Pull request by MShark67**

### CODE REVIEW

**Comment by pyscripter** [comment]
And by the way you are now listed as a contributor!

**Comment by MShark67** [comment]
Thanks!  I finally updated my email address.  As you suggested, that was the issue.  The PaintText procedure works great!  I noticed that if I don't give a BkgColor then it will leave the painted characters slightly darker than they originally were. Maybe it's some combination effect of antialiasing or something like that?   Here's my sample code in case it's an actual issue and not something I'm misunderstanding.

```
procedure TMainForm.SynEdit1PaintTransient(Sender: TObject; Canvas: TCanvas;
  TransientType: TTransientType);
var
  bc: TBufferCoord;
  pt: TPoint;
  c: Char;
  FGColor: TColor;
  BGColor: TColor;
  LRect: TRect;
begin
  if SynEdit1.WordWrap then Exit;
  bc := SynEdit1.CaretXY;
  if not ((bc.Line > 0) and (bc.Line <= SynEdit1.Lines.Count) and
     (bc.Char > 0) and (bc.Char <= Length(SynEdit1.Lines[bc.Line - 1]))) then
    Exit;
  c := SynEdit1.Lines[bc.Line - 1][bc.Char];
  pt := SynEdit1.RowColumnToPixels(SynEdit1.BufferToDisplayPos(bc));
  BGColor := SynEdit1.Color;
  if TransientType = ttAfter then
    FGColor := clFuchsia
  else
    FGColor := Font.Color;
  LRect := Rect(Point(pt.X, pt.Y), Point(pt.X + SynEdit1.CharWidth, pt.Y + SynEdit1.LineHeight));
  // This one leaves the characters looking like the originals.
  // SynEdit1.PaintText(c, Point(0, 0), LRect, SynEdit1.Font.Style, FGColor, BGColor);
  // This one leaves the characters slightly darker than the originals (Consolas 12pt)
  SynEdit1.PaintText(c, Point(0, 0), LRect, SynEdit1.Font.Style, FGColor);
end;

```

**Comment by pyscripter** [comment]
Yes you are right.  I tried a couple of things but I could not get rid of this effect, which is probably due to anti-aliasing.
As it stands if you want to avoid you can either:
-  provide a background or
- invalidate to revert the effect of PaintTransient

In PyScripter I do the latter to implement Ctrl+Click painting (like hyperlink painting, when you hover with Ctrl pressed).

However all these PaintTransient and AfterPaint stuff will become redundant once I implement #160.   It could be used among other things for bracket highlighting.

**Comment by MShark67** [comment]
Great!  It's absolutely not an issue for me as providing a background is easy enough.  Thanks for the update!

**Pull request merged**
