### PR TITLE
Autoindent with Smarttabs bug in case of mix of realtabs and spaces

### PR DESCRIPTION
**Pull request by JaFi-cz**
If code contains combination of real tabs and spaces and both Autoindent and SmartTabs are on, Synedit causes wrong behavior.
This modification switches off Smarttabs for Autoindent action and in case eoTabsTo Spaces is ON it puts spaces instead of the tabs.
The problem is caused by DoTabKey procedure in case SmartTabs are on. 

To demonstrate current bug, create new empty VCL project, add Synedit, SynEditKeyCmds into uses and paste following code into FormCreate and simple press Enter on the end of second line. 
There are 2 bug cases, one for RealTabs, second for Spaces - both settings causes wrong behavior.

```
  with TPSSynedit.Create(self) do
  begin
    Parent := Self;
    Align := alClient;
    WantTabs := True;
    { real tabs bug example. For spaces mode bug example set condition to false }
    if True then
      Options := Options - [eoTabsToSpaces]
    else
      Options := Options + [eoTabsToSpaces];

    Options := Options + [eoAutoIndent, eoSmartTabs, eoSmartTabDelete, eoShowSpecialChars];
    TabWidth := 8;
    Text := 'a'#9'b'#9'c1'#13#9#9'c2';
    CaretY := 2;
    CommandProcessor(ecLineEnd, #0, nil);
    { you should stay on the end of second line, press Enter.
      - for Realtab mode 2 additional spaces are added
      - for spaces wrong number of spaces is added }
  end;
```

### CODE REVIEW

**Comment by pyscripter** [comment]
Could you please create an issue against this PR.

**Comment by pyscripter** [comment]
ExpandTabs is kind of inefficient.

How about something like this instead:

```pascal
  function ExpandTabs(const AInput: string): string;
  var
  I, DestLen: integer;
begin
  DestLen  := 0;
  for I := 1 to Length(AInput) do
  begin
    if AInput[I} = #9 then
      Inc(DestLen, FTabWidth - (DestLen mod FTabWidth))
    else
      Inc(DestLen);
    Result := StringOfChar(' ', DestLen);
  end;
```

**Comment by JaFi-cz** [comment]
Hello
Your code creates corresponding number of spaces in result string. 
Previvous code exchanges tabs to spaces in general string. 
Of course, your code will be more efficient in this specific case  - beginning spaces after autoindent. 

What about include TabsToSpace() and SpaceToTabs() method as public Synedit methods? It can be handy for anybody.

**Comment by pyscripter** [comment]
> What about include TabsToSpace() and SpaceToTabs() method as public Synedit methods? It can be handy for anybody.

It is a good idea.  The right place would be SynEditMiscProcs.pas.   There are a number of routines there named ConvertTabsXYZ, but unfortunately these routines replace tabs with more tabs!  

> Previvous code exchanges tabs to spaces in general string.

Even in that case you are better off calculating the size of the result string and then do the replacement in one pass.  See for instance ConvertTabsEx in SynEditMiscProcs.

**Comment by JaFi-cz** [comment]
I used your ExpandTabs procedure. The problem with viewing diffs is you keep some sources as UTF-8 with BOM (e.g. Synedit.pas), some sources are in ANSI...
Last version I uploaded use same encoding as is Synedit.pas in your source (UTF-8 BOM) but it still shows over 11 000 changes. I give it up. 
Please unite sources encoding.

**Comment by JaFi-cz** [comment]
OK. I downloaded TP Synedit sources, made changes again into synedit.pas and commit it. Now it looks like it works.
SynHighlighterJScript.pas is heavily modified so there is lot of changes in compare to original one.

**Pull request merged**
