### PR TITLE
SynSpellCheck + Englis dictionary, Code folding enabled highlighters

### PR DESCRIPTION
**Pull request by JaFi-cz**

### CODE REVIEW

**Comment by pyscripter** [comment]
- Could you please replace all WideStrings with strings.

**Comment by JaFi-cz** [comment]
Hello
I have bad experiences with Delphi functions like Trim(), UpperCase(), LowerCase...
It doesn't work correctly in some cases. 
This is a reason why I used Widexxx() functions from SynUnicode and now from JCLUnicode.

-- 
Best regards
 Jan Fiala
 ***@***.***

Hello,
úterý 4. května 2021, 23:47:40, napsal jste:

> - Could you please replace all WideStrings with strings.

**Comment by JaFi-cz** [comment]
I found widestring type in the highlighters for keywords lists.

From my pull request it was in following highlighters:
SynHighlighterCPP
SynHighlighterCS
SynHighlighterPHP
SynHighlighterVB

What now, what is better and easier for you? Should I close pull request and make new one or you can use attached sources

-- 
Jan Fiala
***@***.***
ICQ  : 23032692
Web  : http://www.pspad.com
Forum: http://forum.pspad.com


04.05.2021 pyscripter:
> - Could you please replace all WideStrings with strings.

**Comment by pyscripter** [comment]
What you should in your fork is to replace WideStrings with strings, remove the // Fiala comments and commit.

**Comment by pyscripter** [comment]
Thanks.  I am seeing calls to WideTrim.  This function has been removed and the code will not even compile.   Have you checked that the code compiles?

**Comment by JaFi-cz** [comment]
I told you I had problem with standard functions like UpperCase(), LowerCase(). It doesn't work correctly in some ways. So I use WideUpper/WideLower alternatives. They were removed from the SynUnicode, so I use it from JCLUnicode.
WideTrim() and Trim() maybe isn't problem, I will check it.

**Pull request merged**
