### PR TITLE
Html header simplification test.

### PR DESCRIPTION
**Pull request by MShark67**

### CODE REVIEW

**Comment by MShark67** [comment]
This one works in my tests, but so did the other one.  Maybe it will help!

**Comment by pyscripter** [comment]
Still the same issues.  Why did you say that " the "offset" section of the clipboard format is totally wrong (the StartHTML, EndHTML, and start and end fragment numbers.)"   They look correct to me, but if they are not that needs fixing.

**Comment by pyscripter** [comment]
Also the reference to the documentation should be changed to:
https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767917(v=vs.85)

The older link does not work.

**Comment by MShark67** [comment]
The offsets are correct. I was wrong about that completely and mentioned it in the pull request note.  Any idea what may not be working in your tests?  Did it used to work for you?  I don't think I changed any of the actual functionality.  Is there a commit I can look at where it worked before?  I'd like to solve this mystery ;)

**Comment by pyscripter** [comment]
I have no idea.  I think it never worked with Gmail and Thunderbird.  On the other hand it works well with Office applications.  Can you post a small compiled app with Synedit to check whether it works here?

**Comment by MShark67** [comment]
Aha!  I've just tested on a Windows 10 machine and html pasting works in Office apps, but not in gmail!  On my Win 11 machine they all work perfectly.  I have no idea why, but at least now I've seen it fail and can try to find out why.  I'll report back when I have something.

**Comment by pyscripter** [comment]
I am on Windows 11 and still fails.

**Comment by MShark67** [comment]
Darn it lol.  Well at least I've seen it fail now.  What browser do you use for gmail?  Any thoughts on something to try?

**Comment by MShark67** [comment]
And on a humorous note... now it fails three times faster than before!

**Comment by pyscripter** [comment]
I have tried on Edge.  
I have no idea, but I would double check the offsets first and then use some kind of clipboard monitor.
I debugged TSynEditDataObject.GetData with Thunderbird and it does ask for the HTML format first and I assume for some reason is rejected and it then asks for the unicode format.

Excel appears to be asking for the HTML format twice!

**Comment by MShark67** [comment]
Just compared VSCode's clipboard info to ours.  Interesting!  I may have a fix soon.

**Comment by pyscripter** [comment]
By the way what did you use to introspect the clipboard?

**Comment by MShark67** [comment]
I'm just pulling the text back out using the code below.  I've found several differences between what VSCode does and what we do now.  I've got it sorted and now just doing cleanup and testing before a pr.

```
function TSynEditHelper.GetClipboardAsHTML: String;
var
  CF_HTML: Word;
  Data: THandle;
  Ptr: Pointer;
  Error: DWORD;
  Size: NativeUInt;
  utf8: UTF8String;
begin
  Result := '';
  CF_HTML := RegisterClipboardFormat('HTML Format');
  Clipboard.Open;
  try
    Data := Clipboard.GetAsHandle(CF_HTML);
    if Data = 0 then
     raise Exception.Create('HTML data not found on clipboard');
    Ptr := GlobalLock(Data);
    if not Assigned(Ptr) then begin
      Error := GetLastError;
      raise Exception.Create('GlobalLock failed: ' + SysErrorMessage(Error));
    end;
    try
      Size := GlobalSize(Data);
      if Size = 0 then begin
        Error := GetLastError;
        raise Exception.Create('GlobalSize failed: ' + SysErrorMessage(Error));
      end;
      SetString(utf8, PAnsiChar(Ptr), Size - 1);
      Result := String(utf8);
    finally
      GlobalUnlock(Data);
    end;
  finally
    Clipboard.Close;
  end;
end;

```

**Pull request merged**
